server:
  port: 8080

spring:
  application:
    name: gateway-api
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-web
              uri: http://localhost:8081
              predicates:
                - Path=/users/**

            - id: user-api
              uri: http://localhost:8081
              predicates:
                - Path=/api/users/**